server:
  port: 8081

spring:
  dubbo:
    application:
      name: demo-provider
    registry:
      address: zookeeper://172.20.10.4:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.dubbo.service.impl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot-dubbo?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: aa844131681
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml